### ISSUE TITLE
payment gatway select from admin side

### ISSUE THREAD

**Issue by kdwebprtk** [Payop/woocommerce-plugin#7]
i am select payment gatway from my admin side in "Directpay payment method" field but when i am see page after checkout page there is no payment method display.

**Comment by Vertig0** [comment]
Hi.
When you turn off "Directpay payment method" did you see this method in list?

Make sure that this payment method is included in your profile.
Also make sure that this payment method is available for your country.

**Comment by kdwebprtk** [comment]
Hi
Thanks for the replay,
yes, i have the list of payment methods in "Directpay payment method".

i want to multiple select from my wordpress admin

can you please help me for this?
